### ISSUE TITLE
Cannot read property 'ecmaFeatures' of undefined

### ISSUE THREAD

**Issue by bonesoul** [sindresorhus/grunt-eslint#159]
Getting

`Parsing error: Cannot read property 'ecmaFeatures' of undefined`

**Tell us about your environment**

* **ESLint Version:** 5.1.0
* **Node Version:** 10.6.0
* **npm Version:**6.1.0"

my eslintrc

```
env:
  node: true
  es6: true
  jquery: false
  browser: false

extends:
  - eslint:recommended

rules:
  curly: off

```
